# Generated by Django 3.1.5 on 2021-04-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20210401_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='totalprice',
        ),
    ]
