# Generated by Django 3.1.5 on 2021-04-03 18:16

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_remove_cart_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.TextField(),
        ),
    ]
